server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost/simple_wiki?serverTimezone=JST
    username: wiki
    password: hoge00
    driverClassName: com.mysql.cj.jdbc.Driver
    thymeleaf:
      cache: false
      mode: HTML
mybatis.configuration.mapUnderscoreToCamelCase: true
